services:
  taskm_api:
    build:
      context: .
      dockerfile: src/TaskMAPI/Dockerfile
    image: buzigi/taskm-api:latest
    container_name: taskm-api-docker
    restart: unless-stopped
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password123
    volumes:
      - ./src/TaskMAPI:/app/src/TaskMAPI
      - ~/.aspnet/https:/https:ro