services:
  postgres:
    image: postgres:17
    container_name: task_m_postgres
    environment:
      POSTGRES_USER: TaskmUser
      POSTGRES_PASSWORD: TaskmPass
      POSTGRES_DB: TaskMDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: